### ISSUE TITLE
0.3.0: Source Validity Testing E-mail - How does it handle multiple mediasources?

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#43]
@sdrenth 

What would the email look like, if we have multiple mediasources with image sources that become invalid? Does the email display which media source is referenced? 

I could imagine multiple blocks of information - per Mediasource, whereby the name of the Mediasource is being displayed.

![Screenshot 2022-05-11 at 08 45 10](https://user-images.githubusercontent.com/447453/167786138-449aacf9-d93f-4bae-8ad5-71da2cb4c030.png)

**Comment by sdrenth** [comment]
@sonicpunk How about this?

![Screenshot 2022-05-12 at 10 43 38](https://user-images.githubusercontent.com/7802465/168030129-f90f59bc-7f72-4293-9438-332ffa2cc5a1.png)

**Comment by sonicpunk** [comment]
Yes that looks good. 

What about having the emails as chunks, or files, so that we have the ability to customize the emails (colors, maybe add a client logo, etc.)

**Comment by sdrenth** [comment]
@sonicpunk 

### Email template multiple media sources
I was a little bit too quick about this one. Because you need to specify email recipients per media source, it would actually send out an email per media source. (Same applies to the image validity email, this also sends out an email per media source).

So I think we then should keep the template as we had before (see your screenshot in the first comment) and add the media source name in the email topic, so the email subject would become:

Image source validity notice for media source "Uploads" - MODX Revolution

### Custom chunks
We could add this in, I think this should then be specified in the properties of the media source as well. So then I'd need to add setting such as:

- mediamanagerLicenseEmailTpls:
``` {"sourceWrapperTpl": "MyCustomChunkName", "sourceItemTpl": "MyCustomChunkName", "imageWrapperTpl": "MyCustomChunkName", "imageItemTpl": "MyCustomChunkName"}```

This would require setting up the email tpls for every mediasource, but I think that could be helpfull when having different brands in the same CMS.

**Comment by sdrenth** [comment]
@sonicpunk The email templates are still the same. I now include the media source title in the email subject. So for every media source an email is being sent.

If you like me to add the custom chunk feature, could you then create a separate ticket for this?

Example subject:
Image validity notice for media source "uploads" - MODX Revolution
