### ISSUE TITLE
0.3.0: Image Validity Test E-mail - organize Ressources by MODX Context

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/mediamanager#44]
@sdrenth How will multiple MODX Context's be displayed in the email.

I could imaging grouping Resources by MODX Context. In our case, we could end up with a list of resources covering hundreds of articles, for multiple Websites. Having it all in one list could be visually overwhelming and not very helpful.

![Screenshot 2022-05-11 at 08 49 57](https://user-images.githubusercontent.com/447453/167786792-1fa132ee-a6d9-4302-9a37-e35d8602ba5d.png)

**Comment by sdrenth** [comment]
@sonicpunk It's now grouped per context:

![Screenshot 2022-05-12 at 16 10 48](https://user-images.githubusercontent.com/7802465/168095067-e730312c-6044-4828-ae81-70ab2c5beded.png)
![Screenshot 2022-05-12 at 16 10 40](https://user-images.githubusercontent.com/7802465/168095069-dcb1d7a9-6434-434e-b8e0-a87f0c5998aa.png)

**Comment by sonicpunk** [comment]
@sdrenth What happens to archived images? Does the cronjob script ignore those?

**Comment by sonicpunk** [comment]
@sdrenth also what would happen to images that are currently in the old Media Manager that do NOT have a startdate or enddate assigned? Would this trigger an error, or will they be marked as expired?

**Comment by sdrenth** [comment]
@sonicpunk 

> What happens to archived images? Does the cronjob script ignore those?

At the moment these are included. I'll change it so archived images will be ignored.

> also what would happen to images that are currently in the old Media Manager that do NOT have a startdate or enddate assigned? Would this trigger an error, or will they be marked as expired?

It does nothing with those images, because these don't have a license record attached to the image. So these images are not included in the email because there is no license information available. When you edit such an existing file in the mediamanager it will show errors of course, because it will check the required validation rules there such as having to provide a valid image validity start date/end date.
